//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 UTest.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_VIEW_DATARCV                101
#define IDS_VIEW_COMCFG                 103
#define IDS_VIEW_DHVPTL                 109
#define IDS_VIEW_GGAPTL                 111
#define IDS_VIEW_GSVPTL                 113
#define IDS_VIEW_SATDIST                115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_UTestTYPE                   130
#define ID_WINDOW_MANAGER               131
#define IDS_VIEW_ERRCAL                 132
#define IDS_VIEW_CNR                    135
#define IDC_EDGE                        136
#define IDM_CREATION_MODE_TARGET_DCOMP  137
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_DATARCV              312
#define IDD_DIALOG_GGA                  322
#define IDD_DIALOG_ERRCAL               326
#define IDD_DIALOG_SATDIST              328
#define IDD_DIALOG_CNR                  338
#define IDD_DIALOG_PTLSHOW              341
#define IDD_DIALOG_MAP                  342
#define IDD_DIALOG_DHV                  347
#define IDD_DIALOG_GSA                  349
#define IDD_DIALOG_GSV                  353
#define ID_INDICATOR_TIPS               356
#define ID_INDICATOR_COMOPENTIME        357
#define ID_INDICATOR_WORKMODE           358
#define ID_INDICATOR_LINKSTATUS         359
#define ID_INDICATOR_FILEPATH           360
#define ID_INDICATOR_RESTLINE           361
#define IDD_DIALOG_PTLTAB               366
#define IDD_DIALOG_CNO                  367
#define IDD_DIALOG_FRQ_B1I              368
#define IDD_DIALOG_FRQ_B1C              369
#define IDD_DIALOG_FRQ_B2A              370
#define IDD_DIALOG_FRQ_B3I              371
#define IDD_DIALOG_FRQ_L1               372
#define IDD_DIALOG_FRQ_G1               373
#define IDC_COMBO_COM                   1000
#define IDC_BUTTON_OPENCOM              1002
#define IDC_EDIT_SHOWDATA               1007
#define IDC_BUTTON_CLEANEDIT            1008
#define IDC_BUTTON_STOPSHOW             1009
#define IDC_CHECK_SAVEDATA              1010
#define IDC_CHECK_SHOWHEX               1011
#define IDC_BUTTON_SLCTDAT              1012
#define IDC_BUTTON_BGNRPLY              1013
#define IDC_STATIC_LATITUDE             1024
#define IDC_EDIT_LATITUDE               1025
#define IDC_STATIC_LONGITUDE            1026
#define IDC_STATIC_ALTITUDE             1030
#define IDC_EDIT_ALTITUDE               1031
#define IDC_IMAGE_SATDIST               1055
#define IDS_TAB_GSV                     1056
#define IDC_CHECK_BDSPOS                1061
#define IDC_CHECK_GPSPOS                1062
#define IDC_CHECK_GLPOS                 1063
#define IDC_CHECK_GAPOS                 1064
#define IDC_STATIC_BDVISSAT             1065
#define IDC_STATIC_GPVISSAT             1067
#define IDC_STATIC_GLVISSAT             1068
#define IDC_STATIC_GAVISSAT             1069
#define IDC_STATIC_FRQ_B1I              1070
#define IDC_STATIC_FRQ_B1C              1071
#define IDC_STATIC_FRQ_B2A              1072
#define IDC_STATIC_FRQ_B3I              1073
#define IDC_STATIC_FRQ_L1               1074
#define IDC_STATIC_FRQ_G1               1075
#define IDC_BUTTON_CALC                 1076
#define IDC_EDIT_ELERR                  1077
#define IDC_EDIT_HORERR                 1078
#define IDC_STATIC_ELERR                1080
#define IDC_STATIC_HORERR               1081
#define IDC_CHECK_SAVELOG               1082
#define IDC_CHECK_SAVEHEX               1087
#define IDC_EDIT_LONGITUDE              1097
#define IDC_LIST_GSA                    1101
#define IDC_LIST_DHV                    1103
#define IDC_LIST_GGA                    1108
#define IDC_EDIT_DHVDATA                1115
#define IDC_EDIT_GGADATA                1118
#define IDC_LIST_GSV                    1120
#define IDC_EDIT_GSVDATA                1121
#define IDC_EDIT_GSADATA                1122
#define IDC_BUTTON_SELECTHEX            1126
#define IDC_TREE_PTL                    1131
#define IDC_TAB_PTL                     1134
#define IDC_TAB_CNR                     1135
#define IDC_STATIC_USERBLH              1139
#define IDC_STATIC_POSERROR             1140
#define IDC_BUTTON_SETPOS               1141
#define IDC_BUTTON_SEND                 1142
#define IDC_COMBO_COMMAND               1143
#define IDC_LIST_CNO                    1144
#define IDC_EDIT_CNO                    1145
#define IDC_STATIC_VELERR               1146
#define IDC_BUTTON1                     1147
#define ID_SETPORT                      32795
#define ID_DISCONNECT                   32799
#define ID_COM1                         32800
#define ID_COM2                         32801
#define ID_COM3                         32802
#define ID_COM4                         32803
#define ID_COM5                         32804
#define ID_COM6                         32805
#define ID_COM7                         32806
#define ID_COM8                         32807
#define ID_COM9                         32808
#define ID_COM10                        32809
#define ID_COM11                        32810
#define ID_COM12                        32811
#define ID_COM13                        32812
#define ID_COM14                        32813
#define ID_COM15                        32814
#define ID_COM16                        32815
#define ID_COM17                        32816
#define ID_COM18                        32817
#define ID_COM19                        32818
#define ID_COM20                        32819
#define ID_BOTRATE_9600                 32820
#define ID_BOTRATE_115200               32821
#define ID_COM_CFG                      32822

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        374
#define _APS_NEXT_COMMAND_VALUE         32823
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           504
#endif
#endif
